name = "CalibrationTemplateFits"
uuid = "421b3725-5a52-4150-a1b5-2789ece62381"
authors = ["Toby Dixon <toby.dixon.23@ucl.ac.uk>"]
version = "0.1.0"

[deps]

[compat]
Aqua = "0.8.14"
JuliaFormatter = "2"
Test = "1"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "JuliaFormatter"]
